# Generated by Django 4.2.11 on 2024-03-31 22:23

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(default='ancean-no-header-image.png', upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('introduce', models.TextField(default='')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='json')),
                ('wave', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_finish', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('post'), models.Model),
        ),
    ]
