# Generated by Django 4.2.11 on 2024-04-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='/ancean-no-header-image.png', upload_to=''),
        ),
    ]
