# Generated by Django 4.2.7 on 2023-12-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wave',
            field=models.IntegerField(default=0),
        ),
    ]
