# Generated by Django 4.2.11 on 2024-04-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='http://localhost:5050/media/ancean-no-header-image.png', upload_to=''),
        ),
    ]
