# Generated by Django 4.2.8 on 2023-12-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_content_post_is_finish_post_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='json'),
        ),
    ]
