# Generated by Django 4.2.9 on 2024-01-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduce',
            field=models.TextField(default=''),
        ),
    ]
