# Generated by Django 4.2.9 on 2024-01-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='media/ancean-no-header-image.png', upload_to=''),
        ),
    ]
