# Generated by Django 4.2.9 on 2024-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(blank=True, default=[{}], null=True, verbose_name='json'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='ancean-no-header-image.png', upload_to=''),
        ),
    ]
