# Generated by Django 4.2.10 on 2024-03-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_content_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(blank=True, null=True, verbose_name='json'),
        ),
    ]
