# Generated by Django 4.2.11 on 2024-03-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='hello', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
