# Generated by Django 4.2.10 on 2024-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_column='name', max_length=20, unique=True),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='_name',
        ),
    ]
