FROM python:3.9-slim-buster

ENV PYTHONUNBUFFERED 1

WORKDIR /usr/app

COPY /requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

WORKDIR /usr/app

EXPOSE 8000

CMD ["python3", "manage.py" , "runserver", "0.0.0.0:8000", "--settings=ancean.settings.local"]