FROM python:3.9-slim-buster

ENV PYTHONUNBUFFERED 1

WORKDIR /usr/app

COPY requirements.txt .

# Local env use sqlite db
RUN sed '/mysqlclient/d' requirements.txt | tee requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt

WORKDIR /usr/app

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE ancean.settings.local

CMD ["python3", "manage.py" , "runserver", "0.0.0.0:8000", "--settings=ancean.settings.local"]