# Generated by Django 4.2.7 on 2023-12-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
